name: Package

on:
  push:
    tags: v*
    branches:
      - 2.0-feature
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: 'mac'
          - os: windows-latest
            platform: 'win'
          - os: ubuntu-latest
            platform: 'linux'

    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 22.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install
        run: |
          pnpm install --no-frozen-lockfile

      - name: Set env
        if: matrix.platform == 'mac'
        run: |
          echo "APPLEID=${{ secrets.APPLEID }}" >> $GITHUB_ENV
          echo "APPLEIDPASS=${{ secrets.APPLEIDPASS }}" >> $GITHUB_ENV
          echo "CSC_LINK=${{ secrets.CERTIFICATE_OSX_APPLICATION }}" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${{ secrets.CERTIFICATE_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLETEAMID=${{ secrets.APPLETEAMID }}" >> $GITHUB_ENV

      - name: Build
        run: |
          npm run build

      - name: Build App
        run: |
          if [ "${{ matrix.platform }}" == "mac" ]; then
            npm run build:mac
          elif [ "${{ matrix.platform }}" == "win" ]; then
            npm run build:win
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            npm run build:linux
          fi

      - name: GH Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: ''
          prerelease: true
          files: |
            dist/Inkdown*.*
            dist/latest*.yml
